services:
  prolog:
    container_name: prolog
    hostname: prolog
    image: "ghcr.io/lyreplus/budgetflow:latest"
    depends_on:
      - budgetflow-database
    restart: unless-stopped

  budgetflow-database:
    container_name: budgetflow-database
    hostname: budgetflow-database
    image: "postgres"
    env_file:
      - ./env/budgetflow-database.env
    volumes:
      - ./data/budgetflow-database:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:

